// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDThXhQOCkjUJ4L9rSAYNBBFBfWbY0sfsM',
    appId: '1:812957418121:web:d29cf078cd6a1e20ce3c58',
    messagingSenderId: '812957418121',
    projectId: 'syncra-signlogin',
    authDomain: 'syncra-signlogin.firebaseapp.com',
    storageBucket: 'syncra-signlogin.firebasestorage.app',
    measurementId: 'G-TYR95EQ9K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDazABtqDFMWnSbno3O7o9ORXUiCWOs8dk',
    appId: '1:812957418121:android:8fc60c5030b7a93cce3c58',
    messagingSenderId: '812957418121',
    projectId: 'syncra-signlogin',
    storageBucket: 'syncra-signlogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAk-ZHoOxld9LZVtlysrTtaddHxFIgrRM',
    appId: '1:812957418121:ios:02b07b0e92164d0ace3c58',
    messagingSenderId: '812957418121',
    projectId: 'syncra-signlogin',
    storageBucket: 'syncra-signlogin.firebasestorage.app',
    androidClientId: '812957418121-fjbgekr4qbsr7smalg6spmv7ppcrn1c4.apps.googleusercontent.com',
    iosClientId: '812957418121-6m7jk45riilursjqg43fpv1p4ountgg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAk-ZHoOxld9LZVtlysrTtaddHxFIgrRM',
    appId: '1:812957418121:ios:02b07b0e92164d0ace3c58',
    messagingSenderId: '812957418121',
    projectId: 'syncra-signlogin',
    storageBucket: 'syncra-signlogin.firebasestorage.app',
    androidClientId: '812957418121-fjbgekr4qbsr7smalg6spmv7ppcrn1c4.apps.googleusercontent.com',
    iosClientId: '812957418121-6m7jk45riilursjqg43fpv1p4ountgg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDThXhQOCkjUJ4L9rSAYNBBFBfWbY0sfsM',
    appId: '1:812957418121:web:cf837bd5f2aacc4ace3c58',
    messagingSenderId: '812957418121',
    projectId: 'syncra-signlogin',
    authDomain: 'syncra-signlogin.firebaseapp.com',
    storageBucket: 'syncra-signlogin.firebasestorage.app',
    measurementId: 'G-XJ30M58P7L',
  );
}
