class AppStrings {
  const AppStrings._();

  static const String appName = 'Syncra';

  // Login / auth
  static const String loginHeadline = 'Let AI Agent\nApply\nFor You.';
  static const String continueWithGoogle = 'Continue with Google';
  static const String continueWithApple = 'Continue with Apple';
  static const String continueAsGuest = 'Continue as Guest';
  static const String loginTerms =
      'By continuing, you accept our Terms, Privacy Policy, and chat guidelines.';
  static const String signUpTitle = 'Create your account';
  static const String signUpSubtitle = 'Start building your AI-powered career profile';
  static const String createAccount = 'Create account';
  static const String alreadyHaveAccount = 'Already have an account?';
  static const String signIn = 'Sign in';

  // Onboarding
  static const String onboardingHeader = 'Syncra AI Setup';
  static const String goToDashboard = 'Go to Dashboard';

  // Resumes
  static const String resumeListsTitle = 'Resumes';
  static const String myUploads = 'My Uploads';
  static const String aiTailored = 'AI Tailored';
  static const String uploadResume = 'Tap to upload or drag & drop';
  static const String uploadResumeHint = 'PDF, DOC, DOCX up to 5MB • Max 10 at once';
  static const String noResumesTitle = 'No resumes yet';
  static const String noResumesBody =
      'Upload a resume to use it for AI matching, tailoring, and applications.';
  static const String noTailoredTitle = 'No tailored resumes yet';
  static const String noTailoredBody =
      'Tailored resumes generated by Syncra AI will appear here.';

  // Dashboard
  static const String agentLive = 'Agent Live';
  static const String agentIdle = 'Agent Ready';
  static const String activeTask = 'Scraping LinkedIn for Senior UX roles...';
  static const String idleTask = "Tap below to run today's brief";
  static const String askSyncra = 'Ask Syncra anything...';
  static const String askAgentAboutContext = 'Ask agent about this context...';
  static const String approvalPipeline = 'Approval Pipeline';
  static const String reviewApplications = 'Review Applications';
  static const String reviewApplicationsBody =
      "I've tailored 3 resumes and drafted outreach emails. They are waiting for your approval.";
  static const String pending = 'Pending';

  // Chat
  static const String chatTitle = 'Syncra AI 2.5 Pro';
  static const String chatTypingTitle = 'Syncra is drafting...';

  // Jobs
  static const String agentPipeline = 'Pipeline';
  static const String reviewQueue = 'Review Queue';
  static const String history = 'History';
  static const String agentPipelineQueueSubtitle =
      'Syncra lined up your active roles. Review what needs you next.';
  static const String agentPipelineHistorySubtitle =
      'Handled applications, drafts, and agent progress history.';
  static const String searchJobsHint = 'Search roles, companies…';

  // Applications (was Tracker — merged tracker + history into one page)
  static const String applicationsTitle = 'Applications';
  static const String applicationsSubtitle =
      'Every application the agent has filed. Filter by status to find what needs attention.';

  // Notifications
  static const String notificationsTitle = 'Notifications';
  static const String markAllRead = 'Mark all read';

  // Profile
  static const String profileTitle = 'Settings';
  static const String careerPipeline = 'Career Pipeline';
  static const String agentPermissions = 'Agent Permissions & Tools';
  static const String preferences = 'Preferences';
  static const String signOut = 'Sign Out';
}
