class AppStrings {
  const AppStrings._();

  static const String appName = 'Syncra';

  // Login / auth
  static const String loginHeadline = 'Let AI Agent\nApply\nFor You.';
  static const String continueWithGoogle = 'Continue with Google';
  static const String continueWithApple = 'Continue with Apple';
  static const String continueAsGuest = 'Continue as Guest';
  static const String loginTerms =
      'By continuing, you accept our Terms, Privacy Policy, and chat guidelines.';
  static const String signUpTitle = 'Create your account';
  static const String signUpSubtitle = 'Start building your AI-powered career profile';
  static const String createAccount = 'Create account';
  static const String alreadyHaveAccount = 'Already have an account?';
  static const String signIn = 'Sign in';

  // Onboarding
  static const String onboardingHeader = 'Syncra AI Setup';
  static const String goToDashboard = 'Go to Dashboard';

  // Morning brief
  static const String goodMorning = 'Good morning,';

  // Resumes
  static const String resumeListsTitle = 'Resumes';
  static const String myUploads = 'My Uploads';
  static const String aiTailored = 'AI Tailored';
  static const String uploadResume = 'Tap to upload or drag & drop';
  static const String uploadResumeHint = 'PDF, DOC, DOCX up to 5MB • Max 10 at once';
  static const String noResumesTitle = 'No resumes yet';
  static const String noResumesBody =
      'Upload a resume to use it for AI matching, tailoring, and applications.';
  static const String noTailoredTitle = 'No tailored resumes yet';
  static const String noTailoredBody =
      'Tailored resumes generated by Syncra AI will appear here.';

  // Dashboard
  static const String dashboardGreetingRole = 'UX Designer';
  static const String agentLive = 'Agent Live';
  static const String activeTask = 'Scraping LinkedIn for Senior UX roles...';
  static const String askSyncra = 'Ask Syncra anything...';
  static const String askAgentAboutContext = 'Ask agent about this context...';
  static const String approvalPipeline = 'Approval Pipeline';
  static const String reviewApplications = 'Review Applications';
  static const String reviewApplicationsBody =
      "I've tailored 3 resumes and drafted outreach emails. They are waiting for your approval.";
  static const String pending = 'Pending';

  // Chat
  static const String chatInitialMessage =
      'Hi, Syncra AI here. What career goals can I help you execute today?';
  static const String chatTitle = 'Syncra AI 2.5 Pro';
  static const String chatTypingTitle = 'Syncra is drafting...';

  // Jobs
  static const String agentPipeline = 'Pipeline';
  static const String reviewQueue = 'Review Queue';
  static const String history = 'History';
  static const String agentPipelineQueueSubtitle =
      'I processed 142 roles. Here are the ones that need you.';
  static const String agentPipelineHistorySubtitle =
      'Completed actions and timeline history.';
  static const String searchJobsHint = 'Search roles, companies…';

  // Tracker
  static const String trackerTitle = 'Tracker';
  static const String trackerSubtitle =
      'Status of every application the agent submitted.';

  // Notifications
  static const String notificationsTitle = 'Notifications';
  static const String markAllRead = 'Mark all read';

  // Detail / Tailor / Review / Submitted
  static const String matchAnalysis = 'Match analysis';
  static const String requirementChecklist = 'Requirement checklist';
  static const String resumeChanges = 'Recommended resume changes';
  static const String executeApplication = 'Execute Application';
  static const String tailorResume = 'Tailor Resume';
  static const String before = 'Before';
  static const String after = 'After';
  static const String keywordsAdded = 'Keywords added';
  static const String acceptChanges = 'Accept Changes';
  static const String editChanges = 'Edit Changes';
  static const String revertToOriginal = 'Revert to Original Resume';
  static const String reviewApplication = 'Review Application';
  static const String reviewSubtitle = 'You are always in control';
  static const String approveAndAutoApply = 'Approve & Auto Apply';
  static const String applicationSubmitted = 'Application submitted';
  static const String backToHome = 'Back to Home';
  static const String trackApplication = 'Track Application';
  static const String undoSubmission = 'Undo Submission';

  // Profile
  static const String profileTitle = 'Settings';
  static const String careerPipeline = 'Career Pipeline';
  static const String agentPermissions = 'Agent Permissions & Tools';
  static const String agentAutonomy = 'Agent Autonomy';
  static const String autonomySuggest = 'Suggest';
  static const String autonomyAskFirst = 'Ask First';
  static const String autonomyAutoApply = 'Auto-Apply';
  static const String autonomySuggestBody =
      'Agent finds matches and prepares drafts. You decide everything.';
  static const String autonomyAskFirstBody =
      'Agent prepares applications, asks for approval before sending.';
  static const String autonomyAutoApplyBody =
      'Agent applies on your behalf for 90%+ matches. You can intercept anytime.';
  static const String preferences = 'Preferences';
  static const String signOut = 'Sign Out';
}
